name: Static Analysis

# Controls when the workflow will run
on:
  push:
    branches:
      - Develop
  pull_request:
    branches: [Develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detekt:
    name: Detekt
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Runs a single command using the runners shell
      - name: detekt
        run:
            chmod +x gradlew
          ./gradlew detekt


  spotless:
    name: Spotless
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Runs a single command using the runners shell
      - name: spotless
        run:
          chmod +x gradlew
          ./gradlew spotlessCheck